//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAlexa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcumuladoStock
    {
        public short CodigoEmpresa { get; set; }
        public short Ejercicio { get; set; }
        public string CodigoArticulo { get; set; }
        public string CodigoAlmacen { get; set; }
        public short Periodo { get; set; }
        public string Partida { get; set; }
        public string TipoUnidadMedida_ { get; set; }
        public string CodigoColor_ { get; set; }
        public string CodigoTalla01_ { get; set; }
        public decimal UnidadEntrada { get; set; }
        public decimal UnidadSalida { get; set; }
        public decimal UnidadSaldo { get; set; }
        public decimal UnidadCompra { get; set; }
        public decimal UnidadConsumo { get; set; }
        public decimal UnidadEntradaTipo_ { get; set; }
        public decimal UnidadSalidaTipo_ { get; set; }
        public decimal UnidadSaldoTipo_ { get; set; }
        public decimal UnidadCompraTipo_ { get; set; }
        public decimal UnidadConsumoTipo_ { get; set; }
        public decimal ImporteEntrada { get; set; }
        public decimal CosteSalida { get; set; }
        public decimal ImporteSaldo { get; set; }
        public decimal ImporteSalida { get; set; }
        public decimal ImporteCompra { get; set; }
        public decimal ImporteConsumo { get; set; }
        public decimal PrecioMedio { get; set; }
        public decimal PrecioUltimaEntrada { get; set; }
        public decimal PrecioUltimaSalida { get; set; }
        public Nullable<System.DateTime> FechaUltimaEntrada { get; set; }
        public Nullable<System.DateTime> FechaUltimaSalida { get; set; }
        public Nullable<System.DateTime> FechaCaducidad { get; set; }
        public string Ubicacion { get; set; }
        public short StatusRecalculo { get; set; }
        public System.Guid IdAcumuladoStock { get; set; }
    }
}
