//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAlexa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Almacene
    {
        public short CodigoEmpresa { get; set; }
        public string CodigoAlmacen { get; set; }
        public string GrupoAlmacen { get; set; }
        public string Responsable { get; set; }
        public string Almacen { get; set; }
        public string Domicilio { get; set; }
        public string CodigoPostal { get; set; }
        public string CodigoMunicipio { get; set; }
        public string Municipio { get; set; }
        public string CodigoProvincia { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public short AgruparMovimientos { get; set; }
        public string IdDelegacion { get; set; }
        public System.Guid IdAlmacen { get; set; }
    }
}
