//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiAlexa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articulo
    {
        public short CodigoEmpresa { get; set; }
        public string CodigoArticulo { get; set; }
        public string DescripcionArticulo { get; set; }
        public string Descripcion2Articulo { get; set; }
        public string DescripcionLinea { get; set; }
        public string ComentarioArticulo { get; set; }
        public string MarcaProducto { get; set; }
        public string CodigoAlternativo { get; set; }
        public string CodigoAlternativo2 { get; set; }
        public string CodigoArticuloOferta { get; set; }
        public string CodigoArancelario { get; set; }
        public string CodigoProveedor { get; set; }
        public string ReferenciaEdi_ { get; set; }
        public short PublicarInternet { get; set; }
        public string TipoArticulo { get; set; }
        public short Utilizado { get; set; }
        public Nullable<System.DateTime> FechaAlta { get; set; }
        public Nullable<System.DateTime> FechaInicioOferta { get; set; }
        public Nullable<System.DateTime> FechaFinalOferta { get; set; }
        public string Temporada { get; set; }
        public int TipoEnvase_ { get; set; }
        public string UnidadMedida2_ { get; set; }
        public string UnidadMedidaAlternativa_ { get; set; }
        public decimal FactorConversion_ { get; set; }
        public string CodigoFamilia { get; set; }
        public string CodigoSubfamilia { get; set; }
        public string CodigoDivisa { get; set; }
        public string CodigoProyecto { get; set; }
        public string CodigoSeccion { get; set; }
        public string CodigoDepartamento { get; set; }
        public string CodigoDefinicion_ { get; set; }
        public byte ValoracionStock { get; set; }
        public short TratamientoPartidas { get; set; }
        public int ContadorPartida { get; set; }
        public short Colores_ { get; set; }
        public short GrupoTalla_ { get; set; }
        public short AcumulaEstadistica_ { get; set; }
        public short GeneraCompraAutomatica_ { get; set; }
        public short IvaIncluido { get; set; }
        public short BloqueoCompra { get; set; }
        public short BloqueoPedidoCompra { get; set; }
        public short BloqueoAlbaranVenta { get; set; }
        public short BloqueoPedidoVenta { get; set; }
        public decimal UnidadesMinimasOferta { get; set; }
        public decimal UnidadesRegaloOferta { get; set; }
        public decimal StockMinimo { get; set; }
        public decimal StockMaximo { get; set; }
        public decimal PuntoPedido { get; set; }
        public int LotePedido { get; set; }
        public byte GrupoIva { get; set; }
        public byte GrupoIvaCompras { get; set; }
        public decimal PrecioCompra { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal C_Margen { get; set; }
        public decimal CosteFabricacionUnitario { get; set; }
        public decimal PrecioCosteEstandar { get; set; }
        public decimal PrecioVentaconIVA1 { get; set; }
        public decimal PrecioVentaconIVA2 { get; set; }
        public decimal PrecioVentaconIVA3 { get; set; }
        public decimal PrecioVentasinIVA1 { get; set; }
        public decimal PrecioVentasinIVA2 { get; set; }
        public decimal PrecioVentasinIVA3 { get; set; }
        public decimal PrecioOfertaconIVA { get; set; }
        public decimal PrecioOfertasinIVA { get; set; }
        public decimal C_Descuento { get; set; }
        public decimal C_Descuento2 { get; set; }
        public decimal C_Descuento3 { get; set; }
        public decimal C_DescuentoCompras { get; set; }
        public decimal C_DescuentoCompras2 { get; set; }
        public decimal C_DescuentoCompras3 { get; set; }
        public decimal DescuentoOferta { get; set; }
        public short AplicarDescuentos { get; set; }
        public int CodigoComisionista { get; set; }
        public int CodigoComisionista2_ { get; set; }
        public int CodigoComisionista3_ { get; set; }
        public int CodigoComisionista4_ { get; set; }
        public decimal C_Comision { get; set; }
        public decimal C_Comision2_ { get; set; }
        public decimal C_Comision3_ { get; set; }
        public decimal C_Comision4_ { get; set; }
        public decimal PesoBrutoUnitario_ { get; set; }
        public decimal PesoNetoUnitario_ { get; set; }
        public decimal VolumenUnitario_ { get; set; }
        public short FormulaLote { get; set; }
        public short Lote_ { get; set; }
        public short Formula { get; set; }
        public int LoteFabricacion { get; set; }
        public short NivelCompuesto { get; set; }
        public string TipoDemanda { get; set; }
        public short GenerarPlanProd { get; set; }
        public short UsarStockSeg { get; set; }
        public short C_StockSeguridad { get; set; }
        public decimal DemandaMediaDiaria { get; set; }
        public decimal FactorCrecimiento { get; set; }
        public short PeriodosPromediar { get; set; }
        public decimal TasaProduccionDiaria { get; set; }
        public decimal TiempoMedioReposicion { get; set; }
        public short NumDecimalesUnidades { get; set; }
        public short PeriodoVida { get; set; }
        public string TipoABC { get; set; }
        public string CodigoCategoriaLc { get; set; }
        public string CodigoSubcategoriaLc { get; set; }
        public string CodigoClaseArticuloLc { get; set; }
        public string CodigoTipoArticuloLc { get; set; }
        public string CodigoSubtipoArticuloLc { get; set; }
        public string CodigoGrupoArticuloLc { get; set; }
        public string CodigoSubgrupoArticuloLc { get; set; }
        public string CodigoModoLc { get; set; }
        public string CodigoFabricanteLc { get; set; }
        public string CodigoFamiliaFabricanteLc { get; set; }
        public string CodigoConjuntoLc { get; set; }
        public string CodigoSubconjuntoLc { get; set; }
        public decimal MaximoSinRetencionLc { get; set; }
        public short TrataNumerosSerieLc { get; set; }
        public short SonHorasLc { get; set; }
        public short ArticuloNoCodificadoLc { get; set; }
        public short PrecioCosteEditableLc { get; set; }
        public string CodigoTipoPeriodicidadPrecioLc { get; set; }
        public short LiquidableLc { get; set; }
        public string CodigoTipoCoberturaLc { get; set; }
        public short ObsoletoLc { get; set; }
        public string CodigoAreaCompetenciaLc { get; set; }
        public System.Guid ImagenExt { get; set; }
        public short GestionCompras { get; set; }
        public string UnidadMedidaCompras_ { get; set; }
        public string UnidadMedidaVentas_ { get; set; }
        public string UnidadMedidaFabricacion_ { get; set; }
        public string CodigoSerie { get; set; }
        public string UnidadMedidaSerie { get; set; }
        public int FactorPrecioCompra_ { get; set; }
        public int FactorPrecioVenta_ { get; set; }
        public byte TipoUnidadCalculo_ { get; set; }
        public string Medida { get; set; }
        public string TipoArticuloPresupuesto { get; set; }
        public short TipoCodificado { get; set; }
        public string CodigoPeriodicidadPrecio { get; set; }
        public short CobrarDevolucionTardia { get; set; }
        public short CobrarEntregaAdelantada { get; set; }
        public short DevolverDevolucionAdelantada { get; set; }
        public short DevolverEntregaTardia { get; set; }
        public string CodigoArticuloFacturacion { get; set; }
        public decimal PrecioPeriodoRetraso { get; set; }
        public decimal PrecioUnidadPerdida { get; set; }
        public short PartirPeriodos { get; set; }
        public short TipoArticuloAlquiler { get; set; }
        public short NoTraspasarSFA { get; set; }
        public string CodigoContaje { get; set; }
        public short PrecioPorTramos { get; set; }
        public short Suplido { get; set; }
        public short CodigoNacionOrigen { get; set; }
        public short TipoCodigoBarrasSR { get; set; }
        public short PesableSR { get; set; }
        public string ImagenTactilSR { get; set; }
        public decimal TaraUnitaria_ { get; set; }
        public short PrecioModificableSR { get; set; }
        public short NoAgruparSR { get; set; }
        public short EnviaraSR { get; set; }
        public short ImpresionResguardoSR { get; set; }
        public short PeriodoGarantiaSR { get; set; }
        public short NovedadesWeb { get; set; }
        public System.Guid IdArticulo { get; set; }
        public short PublicarGCRM { get; set; }
        public short MesesGarantiaVenta { get; set; }
        public short MesesGarantiaCompra { get; set; }
        public short MesesGarantiaReparacion { get; set; }
    }
}
